### ISSUE TITLE
Provided examples don't work

### ISSUE THREAD

**Issue by justusbluemer** [ip2location/ip2location-deno#1]
Hi,
thanks for your effort to provide a Deno library for your great free IP databases. Unfortunately, I can't get the provided examples to work.

## Uncaught Error: Cannot find module 'big-integer'

With the example in the "Usage" section, I get the following error:

```
❯ deno run --allow-read --allow-env --unstable main.ts

error: Uncaught Error: Cannot find module 'big-integer'
Require stack:
- /Users/justus/code/test-deno-geoip/src/ip2location.js
      const err = new Error(message) as Error & {
                  ^
    at Function._resolveFilename (https://deno.land/std@0.149.0/node/module.ts:407:19)
    at Function._load (https://deno.land/std@0.149.0/node/module.ts:519:29)
    at Module.require (https://deno.land/std@0.149.0/node/module.ts:225:21)
    at require (https://deno.land/std@0.149.0/node/module.ts:1387:16)
    at file:///Users/justus/code/test-deno-geoip/src/ip2location.js:6:14
```

This is with Deno 1.32.5 after download the repo and moving the `src/` folder as well as the `mod.ts` file into the project directory.

`npm install big-integer` solves this immediate issue but subsequent other will remain so it seems like this module isn't actually production-ready.

![CleanShot 2023-04-24 at 12 01 28](https://user-images.githubusercontent.com/6085647/233964977-8351a965-159c-4350-b588-ae2ec22d791c.png)

## Publish on deno.land

Besides the necessary fixes, it would be great if you could publish the updated module on deno.land/x where most Deno modules are hosted. See https://deno.com/add_module for more details.

EDIT: Just FYI the node.js module works flawlessly with Deno when using
```
import {IP2Location, IPTools} from "npm:ip2location-nodejs";
```

**Comment by ip2location-com** [comment]
Hi justusbluemer,

Thanks for reporting the issue. We have investigated the issue and made a new release to fix the issue. Can you please try the new release?

**Comment by justusbluemer** [comment]
@ip2location Perfect, works like a charm now. Thank you!
