### ISSUE TITLE
INVALID_IP_ADDRESS

### ISSUE THREAD

**Issue by kewp** [ip2location/ip2location-deno#2]
Hello.

I've gotten this to work locally on Deno using the ip2location lite bin, but when I send it through to Deno Deploy I get INVALID_IP_ADDRESS. Any idea why?

**Comment by ip2location-com** [comment]
Hi @kewp,

Can you please provide us

1. The name of IP2Location LITE BIN database that you have used?
2. The code that you have tried but not working?

**Comment by kewp** [comment]
hi @ip2location 

The file name was `IP2LOCATION-LITE-DB3.BIN`.
The code looked like this:

```js
const ip2location = new IP2Location();
ip2location.open("./IP2LOCATION-LITE-DB3.BIN");
// get ip address from request
const ip = ...;
const geo = ip2location.getAll(ip);

**Comment by ip2location-com** [comment]
Hi @kewp,

We have tested the provided code on our testing environment, but it is working. Can you please

1. Ensure that you are getting the latest version of the database,
2. Collect the IP addresses that failing the query and send to us?

**Comment by kewp** [comment]
Hi @ip2location 

As I mentioned, it also works for me when I run locally. However it does not work when I try run it from Deno Deploy. Have you tried running it from Deno Deploy?

Karl

**Comment by ip2location-com** [comment]
Hi @kewp,

Can we confirm with you that you are getting the IP address using `request.headers.get`?

**Comment by kewp** [comment]
@ip2location Not sure what you mean. I am definitely getting an ip address ... I print out the IP onto the console, it's exactly the same ip I try while testing from local. It's a normal IP address string.

**Comment by ip2location-com** [comment]
Hi @kewp,

Can you please give us the complete set of the code? We would like to try out on our side.

**Comment by kewp** [comment]
hi @ip2location i will have to figure it out, i've since started using a web service. i'll see if i can reproduce again tomorrow

**Comment by kewp** [comment]
@ip2location I've created a repo https://github.com/kewp/refer-location you can see the deployed version (with the error I was describing) here https://kewp-refer-location.deno.dev/

**Comment by ip2location-com** [comment]
Hi @kewp,

Thanks for the repo, we are trying on Deno Deploy now, meanwhile can you provide us the configuration you used in the project?
![denodeploy1](https://github.com/ip2location/ip2location-deno/assets/6367210/4160e580-019f-4ef6-9a3c-3d342e2ecfa1)

**Comment by kewp** [comment]
@ip2location that does not look like deno deploy. what is that screenshot from?

**Comment by ip2location-com** [comment]
@kewp That's coming from the Deno Deploy dashboard after I choose "Import from GitHub", not sure did we did right to mimic your setup, or can you please share with us on how do you setup on your side?

**Comment by kewp** [comment]
@ip2location don't worry about import from github, just run `deploy.sh` with the right deno deploy key in the environment variable

**Comment by kewp** [comment]
@ip2location just add `export DENO_DEPLOY_TOKEN={insert token here}` above the `deployctl` command in `deploy.sh`

**Comment by ip2location-com** [comment]
Hi @kewp,

Thanks for the information, we are able to reproduce the issue. We found out that the readSync function from node:fs is returning different output for certain points in local and Deno Deploy, and causing all the issues. We have created an [ issue ticket](https://github.com/denoland/deploy_feedback/issues/648) in Deno GitHub repo for further investigation.

**Comment by kewp** [comment]
Ok great hope they fix it @ip2location

**Comment by ip2location-com** [comment]
Hi @kewp ,

We have pushed a fix for the Deno Deploy issue, can you try again with https://deno.land/x/ip2location@8.3.0?

**Comment by kewp** [comment]
yup it works now @ip2location ! https://kewp-refer-location.deno.dev/

**Comment by ip2location-com** [comment]
Hi @kewp,

Glad to hear that! We will close this issue ticket now, but if you encounter another issue, feel free to open a new one to let us know.
